import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import registerServiceWorker from './registerServiceWorker';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/css/bootstrap-theme.css'; 
import 'font-awesome/css/font-awesome.css';
import 'materialize-css/dist/css/materialize.css';
import 'materialize-css/dist/css/materialize.min.css';
import App from './App';
ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
